# not in use
version: '3.8'
services:
  front:
    container_name: 'multi-store-player-front'
    build:
      context: .
      dockerfile: packages/front/.Dockerfile
    command: yarn workspace fomoplayer_front start
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
      - API_PORT=${API_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - REACT_APP_API_PORT=${API_PORT}
      - REACT_APP_API_URL=${API_URL}
  back:
    container_name: 'multi-store-player-back'
    build:
      context: .
      dockerfile: packages/back/.Dockerfile
    command: yarn workspace fomoplayer_back start
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_OIDC_CLIENT_ID=${GOOGLE_OIDC_CLIENT_ID}
      - GOOGLE_OIDC_CLIENT_SECRET=${GOOGLE_OIDC_CLIENT_SECRET}
      - DATABASE_URL=postgres://multi-store-player-docker:${DB_PASSWORD}@pg:5432/multi-store-player
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: 'postgres:12'
    container_name: 'postgres'
    ports:
      - 5432:${DB_PORT_EXTERNAL}
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: multi-store-player-docker
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: multi-store-player
